version: '3.9'

services:
    helloworld-server:
      build:
        context: .
        dockerfile: Dockerfile.server
      networks:
        - envoymesh
      expose:
        - "50051"
      ports:
        - "50051:50051"
    
    envoy:
      build:
        context: .
        dockerfile: Dockerfile.envoy
      volumes:
        - ./envoy.yaml:/etc/envoy.yaml
      networks:
        - envoymesh
      expose:
        - "8888"
        - "1337"
      ports:
        - "8888:8888"
        - "1337:1337"

networks:
  envoymesh: {}