version: '3.9'

services:
    helloworld-server:
      build:
        context: .
        dockerfile: Dockerfile.server
      networks:
        - envoymesh
      expose:
        - "50051"
      ports:
        - "50051:50051"
    
    envoy:
      build:
        context: .
        dockerfile: Dockerfile.envoy
      volumes:
        - ./envoy.yaml:/etc/envoy.yaml
      networks:
        - envoymesh
      expose:
        - "6666"
        - "9999"
      ports:
        - "6666:6666"
        - "9999:9999"

networks:
  envoymesh: {}